#!/bin/sh

uci -q batch <<-EOF
	delete system.ntp.server
	add_list system.ntp.server='0.openwrt.pool.ntp.org
	add_list system.ntp.server='1.openwrt.pool.ntp.org'
	add_list system.ntp.server='2.openwrt.pool.ntp.org'
	add_list system.ntp.server='3.openwrt.pool.ntp.org'
EOF
uci commit system

exit 0
