#!/bin/sh

uci -q batch <<-EOF
	delete system.ntp.server
	add_list system.ntp.server='0.openwrt.pool.ntp.org
	add_list system.ntp.server='1.openwrt.pool.ntp.org'
	add_list system.ntp.server='2.openwrt.pool.ntp.org'
	add_list system.ntp.server='3.openwrt.pool.ntp.org'
EOF
uci commit system

sed -i 's,downloads.immortalwrt.org,downloads.openwrt.org,g' /etc/opkg/distfeeds.conf

exit 0
